import type { NextPage } from 'next'
import { useRouter } from 'next/router'
import Head from 'next/head'
import {
  Box, Heading, Text, Alert,
  AlertIcon,
  AlertTitle,
  AlertDescription,
} from '@chakra-ui/react';

import { PageHeader } from '../components/page-header'
import { Welcome } from '../components/welcome';

const Home: NextPage = () => {
  const { pathname = '', asPath } = useRouter();

  return (
    <>
      <Head>
        <title>{asPath} Physioteam Lappersdorf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_ico.png" />
      </Head>

      <main>
        <Welcome />
      </main>

    </>
  )
}

export default Home
