import type { NextPage } from 'next'
import { useRouter } from 'next/router'
import Head from 'next/head'
import { TeamCard } from '../components/team-card'
import { PageHeader } from '../components/page-header'
import { PageHeading } from '../components/page-heading'

import { Box, SimpleGrid } from '@chakra-ui/react'

const backgroundURL = 'https://ucarecdn.com/c255ca4a-8769-4f01-b2a2-0ac4dd40da6a/-/progressive/yes/-/format/auto/-/resize/2000x/'

const Team: NextPage = () => {
    const { pathname = '', asPath } = useRouter();

    return (
        <>
            <Head>
                <title>{asPath} Physioteam Lappersdorf</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <main>
                <PageHeader backgroundURL={backgroundURL} />
                <PageHeading title="Unser" underlinedTitle='Team' />

                <Box maxW="7xl" mx={'auto'} pt={5} px={{ base: 2, sm: 12, md: 17 }} >
                    <SimpleGrid columns={[1, null, 4]} spacing={2}>
                        <TeamCard name={'Sebastian Sauerer'} photoURL={'https://d35oszxnjbmfnc.cloudfront.net/andreas_mederer.jpg'} position={'Inhaber'} qualifications={['Manuelle Lymphdrainage', 'Manuelle Therapie', 'Fachkraft für Betriebliches Gesundheitsmanagement', 'Augentrainer', 'Progressive Muskel Entspannung (PMR)']}></TeamCard>
                        <TeamCard name={'Sebastian Sauerer'} photoURL={'https://d35oszxnjbmfnc.cloudfront.net/andreas_mederer.jpg'} position={'Inhaber'} qualifications={['Manuelle Lymphdrainage', 'Manuelle Therapie', 'Fachkraft für Betriebliches Gesundheitsmanagement', 'Augentrainer', 'Progressive Muskel Entspannung (PMR)']}></TeamCard>
                        <TeamCard name={'Sebastian Sauerer'} photoURL={'https://d35oszxnjbmfnc.cloudfront.net/andreas_mederer.jpg'} position={'Inhaber'} qualifications={['Manuelle Lymphdrainage', 'Manuelle Therapie', 'Fachkraft für Betriebliches Gesundheitsmanagement', 'Augentrainer', 'Progressive Muskel Entspannung (PMR)']}></TeamCard>
                        <TeamCard name={'Sebastian Sauerer'} photoURL={'https://d35oszxnjbmfnc.cloudfront.net/andreas_mederer.jpg'} position={'Inhaber'} qualifications={['Manuelle Lymphdrainage', 'Manuelle Therapie', 'Fachkraft für Betriebliches Gesundheitsmanagement', 'Augentrainer', 'Progressive Muskel Entspannung (PMR)']}></TeamCard>
                        <TeamCard name={'Sebastian Sauerer'} photoURL={'https://d35oszxnjbmfnc.cloudfront.net/andreas_mederer.jpg'} position={'Inhaber'} qualifications={['Manuelle Lymphdrainage', 'Manuelle Therapie', 'Fachkraft für Betriebliches Gesundheitsmanagement', 'Augentrainer', 'Progressive Muskel Entspannung (PMR)']}></TeamCard>
                        <TeamCard name={'Sebastian Sauerer'} photoURL={'https://d35oszxnjbmfnc.cloudfront.net/andreas_mederer.jpg'} position={'Inhaber'} qualifications={['Manuelle Lymphdrainage', 'Manuelle Therapie', 'Fachkraft für Betriebliches Gesundheitsmanagement', 'Augentrainer', 'Progressive Muskel Entspannung (PMR)']}></TeamCard>
                        <TeamCard name={'Sebastian Sauerer'} photoURL={'https://d35oszxnjbmfnc.cloudfront.net/andreas_mederer.jpg'} position={'Inhaber'} qualifications={['Manuelle Lymphdrainage', 'Manuelle Therapie', 'Fachkraft für Betriebliches Gesundheitsmanagement', 'Augentrainer', 'Progressive Muskel Entspannung (PMR)']}></TeamCard>
                        <TeamCard name={'Sebastian Sauerer'} photoURL={'https://d35oszxnjbmfnc.cloudfront.net/andreas_mederer.jpg'} position={'Inhaber'} qualifications={['Manuelle Lymphdrainage', 'Manuelle Therapie', 'Fachkraft für Betriebliches Gesundheitsmanagement', 'Augentrainer', 'Progressive Muskel Entspannung (PMR)']}></TeamCard>
                        <TeamCard name={'Sebastian Sauerer'} photoURL={'https://d35oszxnjbmfnc.cloudfront.net/andreas_mederer.jpg'} position={'Inhaber'} qualifications={['Manuelle Lymphdrainage', 'Manuelle Therapie', 'Fachkraft für Betriebliches Gesundheitsmanagement', 'Augentrainer', 'Progressive Muskel Entspannung (PMR)']}></TeamCard>
                    </SimpleGrid>
                </Box>
            </main>

        </>
    )
}

export default Team
